Sweet_Delight/Sweet_Delight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('carts/', include('cart.urls')),
    path('admin/', admin.site.urls),
]

# for showing images from database
urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Sweet_Delight/cart/urls.py
from django.urls import path

from .views import *


urlpatterns = [
	path("add-to-cart-<int:food_id>/", AddToCartView.as_view(), name="addtocart"),
	path("my-cart/", MyCartView.as_view(), name="mycart"),
	path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
	path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

	path("checkout/", CheckoutView.as_view(), name="checkout"),

	path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
	path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

	path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
	path("login/", CustomerLoginView.as_view(), name="customerlogin"),
	path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),

	path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
	path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

	path("search/", SearchView.as_view(), name="search"),

	path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
	path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
	path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),
	path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),
	path("admin-order-<int:pk>-change/",
         AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),


]

Sweet_Delight/cart/models.py
from django.db import models
from msilib.schema import Property
from re import T
from turtle import back
from xml.sax.handler import property_declaration_handler
from django.db import models
from django.contrib.auth.models import User
from main.models import FoodMenu

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

# cascade - if one relations' item is deleted, another linked must be deleted
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    joined_on = models.DateTimeField(auto_now_add=True, null=True)
    

    def __str__(self) -> str:
        return self.full_name

class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(FoodMenu, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

Sweet_Delight/templates/adminpages/admin-base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sweet Delight</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- google fonts -->
    <link rel = "stylesheet" href = "{% static 'assets/fonts/font.css' %}">
    <!-- Fontawesome js -->
    <link rel = "stylesheet" href = "{% static 'assets/font-awesome/all.css' %}">
    
    <!-- custom style css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- my custom style css -->
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dokdo" rel="stylesheet">


  </head>
  
  <body>

    <!-- header -->
    <header>
      
     <!-- navbar -->
      <nav class = "navbar">
        <div class = "container">
          <div class = "brand-and-toggler">
            <a class = "navbar-brand">
                <!-- <img src = "{% static 'assets/images/logo.png' %}" alt = "logo"> -->
              <h2>Sweet Delight - Admin</h2>
            </a>
            <button type = "button" id = "navbar-toggler">
              <i class = "fas fa-bars"></i>
            </button>
          </div>
          <div class = "navbar-collapse">
            <ul class = "navbar-nav">
              <li><a  href = "{% url 'adminhome' %}">Home</a></li>
              <li><a  href = "{% url 'adminorderlist' %}">All Orders</a></li>
              <li><a  href = "{% url 'home' %}" target="blank">Visit Site</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- end of navbar -->
      
    </header>
    <!-- end of header -->
{% block content %}

{% endblock content %}
  <!-- contact section -->
  <section class = "padding-y contact" id = "contact"> 
    <div class = "contact-info">
      <div class = "container">
        <div class = "contact-row-2">
          <div class = "contact-col-1">
            <h2>Contact Detail</h2>
            <ul>
              <li>Lakeside, Baidam-6 Pokhara</li>
              <li>Kaski, Nepal 33700</li>
              <li>Contact: +977-061-590999</li>
              <li>Email: sweetdelight@gmail.com</li>
              
            </ul>
          </div>
          <div class = "contact-col-2">
            <h2>Connect With Us</h2>
            <p class = "text"></p>
            <ul class = "center">
              <li class = "center">
                <a href = "#">
                  <i class = "fab fa-facebook-f"></i>
                </a>
              </li>
              <li class = "center">
                <a href = "#">
                  <i class = "fab fa-twitter"></i>
                </a>
              </li>
              <li class = "center">
                <a href = "#">
                  <i class = "fab fa-instagram"></i>
                </a>
              </li>
              <li class = "center">
                <a href = "#">
                  <i class = "fab fa-pinterest"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end of contact section -->

        <footer>
            <p class = "text">Copyright & copy; Sweet Delight Website 2021.</p>
        </footer>
        <!-- end of footer -->
    
    
        <!-- jQuery -->
        <script src = "{% static 'assets/jquery/jquery-3.5.1.js' %}"></script>
        <!-- Fontawesome js -->
        <script src = "{% static 'assets/font-awesome/all.js' %}"></script>
        
        <!-- custom js file -->
        <script src="{% static 'js/script.js' %}"></script>
        <script src="{% static 'js/cart.js' %}"></script>
        
    </body>
  </html> 

Sweet_Delight/templates/adminpages/admin-home.html
{% extends 'adminpages/admin-base.html' %}
{% load static %}

{% block content %}

  <!-- menu section -->
  <section class="padding-y" id = "cart">
    <div class = "container">
        <div class = "checkout-row" style="grid-template-columns: 2fr;">
          <div class = "col-checkout">
            <h3 style="color: #996633; font-weight: 500;
            border-bottom:1px solid #996633;">Pending Orders</h3>
            <div class="box-element">
          
              <div class="order-row">
                <div style="flex:1"><strong>SN</strong></div>
                <div style="flex:1"><strong>Order ID</strong></div> 
                <div style="flex:1"><strong>Customer</strong></div>
                <div style="flex:1"><strong>Ordered On</strong></div>
                <div style="flex:1"><strong>Amount</strong></div>
                
              </div>
              {% for order in pendingorders %}
              <div class="order-row">
                <div style="flex:1">{{forloop.counter}}</div>
                <div style="flex:1"><p><a style="color: blue;" href="{% url 'adminorderdetail' order.id  %}"> #ORDER_{{order.id}}</a></p></div>
                <div style="flex:1">{{order.ordered_by}}</div>
                <div style="flex:1">{{order.created_at}}</div>
                <div style="flex:1">{{order.total|floatformat:2}}</div>
              </div>
              {% endfor %}
      
            </div>
            
          </div>

        </div>
    </div>
  </section>
  <!-- end of menu section -->



{% endblock content %}
    
    

Sweet_Delight/templates/adminpages/admin-order-detail.html
{% extends 'adminpages/admin-base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- menu section -->
<section class="padding-y" id = "cart">
    <div class = "container">
        <div class = "checkout-row" style="grid-template-columns: 2fr 2fr;">
          <div class = "col-checkout" id="form-wrapper">
            <h3 style="color: #996633; font-weight: 500; 
            border-bottom:1px solid #996633;">Order Detail</h3>
              <div class="text">
                  <p><span style="font-weight: bold;">Order ID:   </span> #ORDER_{{  ord_obj.id}} </p>
                  <p><span style="font-weight: bold;">Order Status: </span>{{ord_obj.order_status}} </p>
                  <p><span style="font-weight: bold;">Ordered On: </span>  {{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago) </p>
                  <p><span style="font-weight: bold;">Customer Information: </span> By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}, {{ord_obj.email}} </p>
                  <p><span style="font-weight: bold;">Shipping Address: </span> By {{ord_obj.shipping_address}}</p>
                  <p><span style="font-weight: bold;">Payment Information: </span> Using {{ord_obj.payment_method}}
                    ({% if ord_obj.payment_completed %}
                    Payment Completed
                    {% else %}
                    Not Paid
                    {% endif %})</p>

              </div>
          </div>
          <div class = "col-checkout">
            <h3 style="color: #996633; font-weight: 500;
            border-bottom:1px solid #996633;">Ordered Items</h3>
            <div class="box-element">
          
              <div class="order-row">
                <div style="flex:1"><strong>SN</strong></div>
                <div style="flex:1"><strong>Item</strong></div>
                <div style="flex:1"><strong>Rate</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Subtotal</strong></div>
              </div>
              {% for cp in ord_obj.cart.cartproduct_set.all %}
              <div class="order-row">
                <div style="flex:1"><p>{{forloop.counter}}</p></div>
                <div style="flex:1"><p>{{cp.product.item_name}}({{cp.product.id}})</p></div>
                <div style="flex:1"><p>{{cp.rate}}</p></div>
                <div style="flex:1"><p>{{cp.quantity}}</p></div>
                <div style="flex:1"><p>Rs. {{cp.subtotal}}</p></div>
              </div>
              {% endfor %}
              <h5>Total: Rs. {{ord_obj.total|floatformat:2|intcomma}}</h5>
            </div>
          </div>
        </div>
        <form action="{% url 'adminorderstatuschange' ord_obj.id %}" method="POST">
            {% csrf_token %}
            <select name="status">
                {% for i, j in allstatus %}
                <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                {% endfor %}
            </select>
            <button class="button btn-blue" style="padding: 6px;">Change</button>
            
        </form>
    </div>
  </section>
  <!-- end of menu section -->



{% endblock content %}
    
    

Sweet_Delight/templates/adminpages/admin-order-list.html
{% extends 'adminpages/admin-base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

 <!-- menu section -->
 <section class="padding-y" id = "cart">
    <div class = "container">
        <div class = "checkout-row" style="grid-template-columns: 2fr;">
          <div class = "col-checkout">
            <h3 style="color: #996633; font-weight: 500;
            border-bottom:1px solid #996633;">All Orders</h3>
            <div class="box-element">
          
              <div class="order-row">
                <div style="flex:1"><strong>SN</strong></div>
                <div style="flex:1"><strong>Order ID</strong></div> 
                <div style="flex:1"><strong>Customer</strong></div>
                <div style="flex:1"><strong>Ordered On</strong></div>
                <div style="flex:1"><strong>Amount</strong></div>
                <div style="flex:1"><strong>Status</strong></div>
                
              </div>
              {% for order in allorders %}
              <div class="order-row">
                <div style="flex:1">{{forloop.counter}}</div>
                <div style="flex:1"><p><a style="color: blue;" href="{% url 'adminorderdetail' order.id  %}"> #ORDER_{{order.id}}</a></p></div>
                <div style="flex:1">{{order.ordered_by}}</div>
                <div style="flex:1">{{order.created_at}}</div>
                <div style="flex:1">{{order.total|floatformat:2}}</div>
                <div style="flex:1">{{order.order_status}}</div>
              </div>
              {% endfor %}
      
            </div>
            
          </div>
        </div>
    </div>
  </section>
  <!-- end of menu section -->


{% endblock content %}
    
    

Sweet_Delight/templates/adminpages/adminlogin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login Form</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/log.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800&display=swap" rel="stylesheet">
</head>
<body>
  <div class="cont">

    <!-- sign-in form -->
    <div class="form sign-in">
      <h2>Admin Sign In</h2>

      <form action ="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="submit" type="submit">Sign In as Admin</button>
        
        {% if error %}
        <li style="color: red;">{{error}}</li>
        {% endif %}
        <p class="forgot-pass">Forgot Password ?</p>
      </form>
         

    </div>

    <div class="sub-cont">
      <div class="img">
        <div class="img-text m-up">
          <h2>Welcome to login!</h2>
          <p></p>
        </div>
        
        <!-- <div class="img-btn">
         <span class="button" href="register/">Sign Up</span> 
        </div> -->

      </div>
  </div>

</body>
</html>